#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
MEMOIR_HOME=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )

MEMOIR_ENV="${MEMOIR_HOME}/install/bin/memoir-env"

if [ ! -f ${MEMOIR_ENV} ] ; then
    printf "\e[31m;1mmemoir is not installed in its usual location!\e[0m\n"
    printf "  Add the installation to your PATH"
fi

source ${MEMOIR_ENV}
