#!/bin/bash

GIT_ROOT=`git rev-parse --show-toplevel` ;

. ${GIT_ROOT}/compiler/noelle/enable ;

PERONI_LLVM=/project/extra/llvm/9.0.0/enable ;
if [ -f ${PERONI_LLVM} ] ; then
   . ${PERONI_LLVM} ;
fi

echo "MemOIR toolchain sourced." ;
