BUILD_DIR=build
BINARY_NAME=$(shell basename ${PWD})
CFILES=$(wildcard *.c)
CXXFILES=$(wildcard *.cpp)
EXTRA_CFLAGS=
EXTRA_CXXFLAGS=
OPTFLAGS=$(shell [ -f optflags ] && cat optflags)

include ../../Makefile.include
