#!/bin/bash -e
SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
MEMOIR_HOME=$(realpath $( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..)

LIB_DIR=${MEMOIR_HOME}/lib

NOELLE_LOAD=${MEMOIR_HOME}/bin/noelle-load

# ${NOELLE_LOAD} -load ${LIB_DIR}/memoir.so --memoir-cl "$@"
opt -load-pass-plugin=${MEMOIR_HOME}/lib/Noelle.so -load-pass-plugin=${MEMOIR_HOME}/lib/memoir.so -load-pass-plugin=${MEMOIR_HOME}/lib/folio.so -passes='folio,memoir-reify-temp-args' "$@"
