#!/bin/bash -e
GIT_ROOT=`git rev-parse --show-toplevel` ;
LIB_DIR=${GIT_ROOT}/install/lib ;

source ${GIT_ROOT}/enable ;

LOAD_CL=$(find ${LIB_DIR} -name "CommandLine.so" -printf ' -load %p ')
LOAD_OTHER=$(find ${LIB_DIR} -name "*.so" -not -name "CommandLine.so" -printf ' -load %p ')
LOAD_PASSES="${LOAD_CL} ${LOAD_OTHER}"

noelle-load "${LOAD_PASSES}" --memoir-cl "$@"
