#!/bin/bash

SOURCE=${BASH_SOURCE[0]}
while [ -L "${SOURCE}" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "${SOURCE}")
  # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
  [[ ${SOURCE} != /* ]] && SOURCE=$DIR/$SOURCE 
done
GIT_ROOT=$( cd -P "$( dirname "${SOURCE}" )" >/dev/null 2>&1 && pwd )/..

PERONI_LLVM=/project/extra/llvm/9.0.0/enable
if [ -f ${PERONI_LLVM} ] ; then
   . ${PERONI_LLVM}
fi

export PATH=${GIT_ROOT}/bin:${PATH}
export LD_LIBRARY_PATH=${GIT_ROOT}/lib:${PATH}
