#!/bin/bash -e

function usage {
    echo "This script will run MemOIR optimizations and lower to LLVM IR." ;
    echo "  USAGE: `basename $0` <INPUT IR FILE> <OUTPUT IR FILE> [<OPTIONS, ...>]" ;
}

if [[ $# -le 1 ]] ; then
    usage
    exit 1
fi

GIT_ROOT=`git rev-parse --show-toplevel` ;
LIB_DIR=${GIT_ROOT}/install/lib ;

source ${GIT_ROOT}/enable ;

INPUT_IR_FILE="$1" ;
OUTPUT_IR_FILE="$2" ;

echo "Running MemOIR optimization pipeline (I: ${INPUT_IR_FILE}, O: ${OUTPUT_IR_FILE})" ;

# Normalize the bitcode
${GIT_ROOT}/compiler/scripts/memoir-norm ${INPUT_IR_FILE} ${OUTPUT_IR_FILE} ;

# Lower the bitcode
${GIT_ROOT}/compiler/scripts/memoir-lower ${INPUT_IR_FILE} ${OUTPUT_IR_FILE} ;
