#!/bin/bash -e

function usage {
    echo "This script will normalize an LLVM program to be a MEMOIR program.";
    echo "  USAGE: `basename $0` <INPUT FILE> -o <OUTPUT FILE> [<OPTIONS, ...>]"
}

function flags {
    echo "  FLAGS:"
    echo "    -h,--help              Display this help message."
    echo "    -o,--output <filename> Specifies the output file."
    echo "    --stats                Print statistics about the MEMOIR program."
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

PREPASSES=()
POSTPASSES=()

while [[ $# -gt 0 ]] ;
do
    case $1 in
        -o|--output)
            OUTPUT_IR_FILE=$2
            shift
            shift
            ;;
        -h|--help)
            usage
            echo ""
            flags
            exit 1
            ;;
        --stats)
            PREPASSES+=("--memoir-stats")
            POSTPASSES+=("--memoir-stats")
            shift
            ;;
        *)
            if [ -n "${INPUT_IR_FILE}" ] ; then
                echo "Too many positional arguments passed!"
                usage
                exit 1
            fi
            INPUT_IR_FILE=$1
            shift
            ;;
    esac
done

if [ -z ${INPUT_IR_FILE} ] ; then
    echo "No input IR file specified."
    usage
    exit 1
fi

if [ -z ${OUTPUT_IR_FILE} ] ; then
    echo "No output IR file specified."
    usage
    exit 1
fi

IR_FILE=$(mktemp --suffix=.bc)
cp ${INPUT_IR_FILE} ${IR_FILE}

# Run some generally helpful LLVM transformations.
opt --always-inline -mem2reg -argpromotion -sroa --break-crit-edges ${IR_FILE} -o ${IR_FILE}

# Run NOELLE norm so that it is happy.
noelle-norm ${IR_FILE} -o ${IR_FILE}

# ${MEMOIR_HOME}/bin/memoir-prof ${IR_FILE} ${IR_FILE_PROF} ;

# Link in the IR declarations.
llvm-link ${IR_FILE} $(memoir-config --libdir)/memoir.decl.bc -o ${IR_FILE}

# Run SSA construction and type inference.
memoir-load ${PREPASSES[@]} --memoir-type-infer --mut2immut ${POSTPASSES[@]} ${IR_FILE} -o ${IR_FILE}

mv ${IR_FILE} ${OUTPUT_IR_FILE}
