#!/bin/bash -e

function usage {
    echo "This script will run MemOIR optimizations.";
    echo "  USAGE: `basename $0` <INPUT FILE> -o <OUTPUT FILE> [<OPTIONS, ...>]"
}

function flags {
    echo "  FLAGS:" 
    echo "    -o,--output <FILENAME>" 
    echo "      Specifies the output file" 
}

if [[ $# -lt 1 ]]; then
    usage
    exit 1
fi

PASSES=()

while [[ $# -gt 0 ]] ;
do
    case $1 in
        -o|--output)
            OUTPUT_IR_FILE=$2
            shift
            shift
            ;;
        -h|--help)
            usage
            echo ""
            flags
            exit 1
            ;;
        *)
            if [ -n "${INPUT_IR_FILE}" ] ; then
                echo "Too many positional arguments passed!"
                usage
                exit 1
            fi
            INPUT_IR_FILE=$1
            shift
            ;;
    esac
done

if [ -z ${INPUT_IR_FILE} ] ; then
    echo "No input IR file specified."
    usage
    exit 1
fi

if [ -z ${OUTPUT_IR_FILE} ] ; then
    echo "No output IR file specified."
    usage
    exit 1
fi

TEMP_DIR=$(mktemp --directory)
IMPL_CPP_FILE=${TEMP_DIR}/impl.cpp
IMPL_IR_FILE=${TEMP_DIR}/impl.bc
IR_FILE=${TEMP_DIR}/lowering.bc

cp ${INPUT_IR_FILE} ${IR_FILE}

# Run Folio.
folio ${IR_FILE} -o ${IR_FILE}

# Run the ImplLinker.
memoir-load ${IR_FILE} -passes=memoir-impl-linker --impl-out-file ${IMPL_CPP_FILE} -o ${IR_FILE}

# Compile the collection implementations to bitcode.
clang++ ${IMPL_CPP_FILE} -O3 -c -emit-llvm -I$(memoir-config --includedir) -std=c++17 -o ${IMPL_IR_FILE}

# Link the bitcode.
llvm-link ${IR_FILE} ${IMPL_IR_FILE} -o ${IR_FILE}

# Peform SSA destruction.
memoir-load -passes=memoir-lower-fold,memoir-ssa-destruction ${IR_FILE} -o ${OUTPUT_IR_FILE}

# Cleanup.
rm -rf ${TEMP_DIR}
