GIT_ROOT=

BUILD_DIR=build

CC=clang++
LL=llvm-link
OPT=$(GIT_ROOT)/compiler/scripts/optimize.sh
CFLAGS=-I$(GIT_ROOT)/runtime/include -std=c++17 -O1 -Xclang -disable-llvm-passes
LIBS=-lm

IR_FILE=$(BUILD_DIR)/all_in_one.bc
OBJ_FILE=$(patsubst %.bc,%.o,$(IR_FILE))
BINARY=$(patsubst %.bc,%,$(IR_FILE))


CFILES := $(wildcard *.c)
CPPFILES := $(wildcard *.cpp)
C_BITCODES := $(patsubst %.c,$(BUILD_DIR)/%.bc,$(CFILES))
CPP_BITCODES :=  $(patsubst %.cpp,$(BUILD_DIR)/%.bc,$(CPPFILES))

all: build test

compile: $(BUILD_DIR) $(BINARY)

test: build
	$(BUILD_DIR)/all_in_one &> out.txt

$(BUILD_DIR):
	mkdir -p $(BUILD_DIR)

$(C_BITCODES): $(BUILD_DIR)/%.bc : %.c
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@

$(CPP_BITCODES): $(BUILD_DIR)/%.bc : %.cpp
	$(CC) $(CFLAGS) -emit-llvm -c $< -o $@

$(IR_FILE): $(C_BITCODES) $(CPP_BITCODES)
	$(LL) $^ $(GIT_ROOT)/runtime/build/objectir.bc -o $@
	$(OPT) $@

$(OBJ_FILE): $(IR_FILE)
	llc -filetype=obj $< -o $@

$(BINARY): $(OBJ_FILE)
	$(CC) $< -o $@

.PHONY: clean all test compile

clean:
	rm -f *~ *.bc
